/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 fullDeskSetup.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from "framer-motion-3d";

export function DeskSetup(props) {
  const { nodes, materials } = useGLTF('/fullDeskSetup.glb');
  const { section } = props;
  return (
    <group {...props} dispose={null}>
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube006.geometry} material={materials.Aluminium} position={[0.292, 4.307, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube007.geometry} material={materials.Aluminium} position={[0.292, 2.582, 0.294]} rotation={[-Math.PI, 0.014, Math.PI / 2]} />
      <motion.mesh animate={{scale: section ===0 ? [0.028, 0.041, 0.028] : [0, 0, 0]}} geometry={nodes.Cylinder.geometry} material={materials.Aluminium} position={[1.706, 2.486, 0.283]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? [0.028, 0.041, 0.028] : [0, 0, 0]}} geometry={nodes.Cylinder001.geometry} material={materials.Aluminium} position={[1.725, 2.516, -1.132]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? [0.028, 0.041, 0.028] : [0, 0, 0]}} geometry={nodes.Cylinder002.geometry} material={materials.Aluminium} position={[-1.114, 2.486, 0.245]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? [0.028, 0.041, 0.028] : [0, 0, 0]}} geometry={nodes.Cylinder003.geometry} material={materials.Aluminium} position={[-1.095, 2.516, -1.171]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube001.geometry} material={materials.DarkMetal} position={[0.293, 2.638, 0.264]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube008.geometry} material={materials.DarkMetal} position={[0.312, 2.663, -1.152]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.019 : 0}} geometry={nodes.Cylinder004.geometry} material={materials.Aluminium} position={[1.702, 2.487, 0.283]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.019 : 0}} geometry={nodes.Cylinder005.geometry} material={materials.Aluminium} position={[-1.054, 2.487, 0.246]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.019 : 0}} geometry={nodes.Cylinder006.geometry} material={materials.Aluminium} position={[1.722, 2.516, -1.132]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.019 : 0}} geometry={nodes.Cylinder007.geometry} material={materials.Aluminium} position={[-1.035, 2.516, -1.17]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube009.geometry} material={materials.DarkMetal} position={[0.302, 2.305, -0.426]} rotation={[0, 1.557, 0.014]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.01, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder008.geometry} material={materials.DarkMetal} position={[0.827, 2.264, -1.144]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.01, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder009.geometry} material={materials.DarkMetal} position={[-0.207, 2.264, -1.159]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.01, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder010.geometry} material={materials.DarkMetal} position={[-0.227, 2.255, 0.257]} rotation={[3.142, -1.557, -0.006]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.01, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder011.geometry} material={materials.DarkMetal} position={[0.807, 2.255, 0.271]} rotation={[3.142, -1.557, -0.006]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube010.geometry} material={materials.DarkMetal} position={[0.29, 2.252, 0.471]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube011.geometry} material={materials.DarkMetal} position={[1.695, 2.231, 0.37]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube012.geometry} material={materials.DarkMetal} position={[-1.094, 2.231, 0.332]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder012.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder013.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder014.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder015.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder016.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder017.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder018.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cylinder019.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}}  geometry={nodes.Cube013.geometry} material={materials.DarkMetal} position={[0.301, 2.301, -0.396]} rotation={[0, 1.557, 0.007]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube014.geometry} material={materials.DarkMetal} position={[0.311, 2.301, -0.396]} rotation={[0, 1.557, 0.007]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.006, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder020.geometry} material={nodes.Cylinder020.material} position={[0.864, 2.225, -0.964]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.006, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} position={[0.849, 2.225, 0.094]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.006, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} position={[-0.253, 2.225, -0.979]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.019, 0.006, 0.019] : [0, 0, 0]}} geometry={nodes.Cylinder023.geometry} material={nodes.Cylinder023.material} position={[-0.268, 2.225, 0.078]} rotation={[3.142, -1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.3, 0.3, 0.296] : [0, 0, 0]}} geometry={nodes.Cube015.geometry} material={materials.DarkMetal} position={[0.292, 4.382, 0.294]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 0.376 : 0}} geometry={nodes.Cube017.geometry} material={materials.DarkMetal} position={[0.303, 1.944, -0.456]} rotation={[0, 1.557, 0.313]} />
      <motion.mesh animate={{scale: section ===0 ? [0.054, 0.186, 0.054] : [0, 0, 0]}} geometry={nodes.Cylinder024.geometry} material={materials.DarkMetal} position={[0.289, 1.201, 0.504]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.32, 0.511, 0.32] : [0, 0, 0]}} geometry={nodes.Cylinder025.geometry} material={materials.Aluminium} position={[0.289, 0.655, 0.504]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? [0.22, 0.11, 0.22] : [0, 0, 0]}} geometry={nodes.Cylinder026.geometry} material={materials.Aluminium} position={[0.289, 0.49, 0.504]} rotation={[0, 1.557, 0]} />
      <motion.mesh animate={{scale: section ===0 ? 1.44 : 0}} geometry={nodes.Plane001.geometry} material={materials.Mesh} position={[0.301, 2.602, -0.431]} rotation={[0, 1.557, 0.003]} />
      <motion.mesh animate={{scale: section ===0 ? 1.434 : 0}} geometry={nodes.Plane002.geometry} material={materials.Mesh} position={[0.277, 4.705, 1.374]} rotation={[0, 1.557, -1.571]} />
      <motion.mesh animate={{scale: section ===0 ? 0.207 : 0}} geometry={nodes.Cylinder027.geometry} material={materials.Kevlar} position={[0.308, 1.482, -0.61]} rotation={[0, 1.557, 0.46]} />
      <motion.mesh animate={{scale: section ===0 ? [0.022, 0.047, 0.022] : [0, 0, 0]}} geometry={nodes.Cylinder028.geometry} material={nodes.Cylinder028.material} position={[1.575, 0.152, -1.339]} rotation={[Math.PI / 2, 0, -1.557]}/>
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle001.geometry} material={materials.Kevlar} position={[1.607, 0.152, -1.338]} rotation={[Math.PI / 2, 0, -1.557]}/>
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle002.geometry} material={materials.Kevlar} position={[1.542, 0.152, -1.339]} rotation={[-Math.PI / 2, 0, 1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle.geometry} material={materials.DarkMetal} position={[1.575, 0.152, -1.339]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? [0.022, 0.047, 0.022] : [0, 0, 0]}} geometry={nodes.Cylinder029.geometry} material={nodes.Cylinder029.material} position={[-0.945, 0.152, -1.373]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle003.geometry} material={materials.Kevlar} position={[-0.912, 0.152, -1.373]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle004.geometry} material={materials.Kevlar} position={[-0.978, 0.152, -1.374]} rotation={[-Math.PI / 2, 0, 1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle005.geometry} material={materials.DarkMetal} position={[-0.945, 0.152, -1.373]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? [0.022, 0.047, 0.022] : [0, 0, 0]}} geometry={nodes.Cylinder030.geometry} material={nodes.Cylinder030.material} position={[-1.875, 0.152, 1.162]} rotation={[Math.PI / 2, 0, 2.981]}/>
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle006.geometry} material={materials.Kevlar} position={[-1.88, 0.152, 1.13]} rotation={[Math.PI / 2, 0, 2.981]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle007.geometry} material={materials.Kevlar} position={[-1.87, 0.152, 1.194]} rotation={[-Math.PI / 2, 0, -2.981]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle008.geometry} material={materials.DarkMetal} position={[-1.875, 0.152, 1.162]} rotation={[Math.PI / 2, 0, 2.981]} />
      <motion.mesh animate={{scale: section ===0 ? [0.022, 0.047, 0.022] : [0, 0, 0]}} geometry={nodes.Cylinder031.geometry} material={nodes.Cylinder031.material} position={[2.392, 0.152, 1.287]} rotation={[Math.PI / 2, 0, 1.021]}/>
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle009.geometry} material={materials.Kevlar} position={[2.364, 0.152, 1.304]} rotation={[Math.PI / 2, 0, 1.021]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle010.geometry} material={materials.Kevlar} position={[2.42, 0.152, 1.27]} rotation={[-Math.PI / 2, 0, -1.021]}  />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle011.geometry} material={materials.DarkMetal} position={[2.392, 0.152, 1.287]} rotation={[Math.PI / 2, 0, 1.021]}  />
      <motion.mesh animate={{scale: section ===0 ? [0.022, 0.047, 0.022] : [0, 0, 0]}} geometry={nodes.Cylinder032.geometry} material={nodes.Cylinder032.material} position={[0.314, 0.152, 2.757]} rotation={[Math.PI / 2, 0, 1.021]}/>
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle012.geometry} material={materials.Kevlar} position={[0.287, 0.152, 2.774]} rotation={[Math.PI / 2, 0, 1.021]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle013.geometry} material={materials.Kevlar} position={[0.342, 0.152, 2.74]} rotation={[-Math.PI / 2, 0, -1.021]} />
      <motion.mesh animate={{scale: section ===0 ? 0.15 : 0}}  geometry={nodes.Circle014.geometry} material={materials.DarkMetal} position={[0.314, 0.152, 2.757]} rotation={[Math.PI / 2, 0, 1.021]} />
      <motion.mesh animate={{scale: section ===0 ? 0.03 : 0}} geometry={nodes.Circle015.geometry} material={materials.Kevlar} position={[1.804, 4.454, -0.449]} rotation={[-1.501, -0.001, 1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.03 : 0}} geometry={nodes.Circle016.geometry} material={materials.Kevlar} position={[-1.199, 4.454, -0.491]} rotation={[1.641, 0.001, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? [0.06, 0.025, 0.085] : [0, 0, 0]}} geometry={nodes.Cube016.geometry} material={materials.Kevlar} position={[-1.296, 4.336, 0.078]} rotation={[0, 1.557, 0.041]} />
      <motion.mesh animate={{scale: section ===0 ? [0.06, 0.025, 0.085] : [0, 0, 0]}} geometry={nodes.Cube022.geometry} material={materials.Kevlar} position={[1.881, 4.337, 0.122]} rotation={[0, 1.557, 0.041]} />
      <motion.mesh animate={{scale: section ===0 ? 0.06 : 0}} geometry={nodes.Circle017.geometry} material={materials.Kevlar} position={[0.896, 2.145, -0.874]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.06 : 0}} geometry={nodes.Circle018.geometry} material={materials.Kevlar} position={[-0.278, 2.145, -0.89]} rotation={[-Math.PI / 2, 0, 1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cylinder033.geometry} material={materials.Kevlar} position={[1.478, 2.001, -0.62]} rotation={[2.792, 0.013, -1.566]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cylinder034.geometry} material={materials.Kevlar} position={[-0.892, 2.001, -0.652]} rotation={[2.792, 0.013, 1.575]} />
      <motion.mesh animate={{scale: section ===0 ? [0.069, 0.785, 0.785] : [0, 0, 0]}} geometry={nodes.Cube023.geometry} material={materials.Leather} position={[0.276, 4.09, 1.458]} rotation={[0, 1.557, 0.075]} />
      <motion.mesh animate={{scale : section===0 ? 1 : 0}} geometry={nodes.Cube024.geometry} material={materials.Leather} position={[0.278, 3.851, 1.36]} rotation={[0, 1.557, 0.146]} />
      <motion.mesh animate={{scale : section===0 ? 1 : 0}} geometry={nodes.Cube025.geometry} material={materials.Leather} position={[0.277, 4.229, 1.383]} rotation={[0, 1.557, 0.351]} />
      <motion.mesh animate={{scale: section ===0 ? 0.206 : 0}} geometry={nodes.Circle019.geometry} material={materials.Kevlar} position={[1.773, 4.27, 1.241]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.206 : 0}} geometry={nodes.Circle020.geometry} material={materials.Kevlar} position={[1.774, 3.85, 1.221]} rotation={[Math.PI / 2, 0, -1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.206 : 0}} geometry={nodes.Circle021.geometry} material={materials.Kevlar} position={[-1.216, 3.85, 1.181]} rotation={[-1.484, -0.001, 1.557]}  />
      <motion.mesh animate={{scale: section ===0 ? 0.206 : 0}} geometry={nodes.Circle022.geometry} material={materials.Kevlar} position={[-1.216, 4.271, 1.198]} rotation={[-1.484, -0.001, 1.557]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube002.geometry} material={materials.Kevlar} position={[-1.505, 4.357, 0.074]} rotation={[0, 1.557, 0.043]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube003.geometry} material={materials.Kevlar} position={[2.095, 4.382, 0.125]} rotation={[0, 1.557, 0.043]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube004.geometry} material={materials.Kevlar} position={[2.095, 4.357, 0.124]} rotation={[0, 1.557, 0.043]} />
      <motion.mesh animate={{scale: section ===0 ? [0.217, 0.3, 0.223] : [0, 0, 0]}} geometry={nodes.Cube005.geometry} material={materials.Kevlar} position={[2.095, 4.237, 0.119]} rotation={[0, 1.557, 0.043]} />
      <motion.mesh animate={{scale: section ===0 ? [0.217, 0.3, 0.223] : [0, 0, 0]}} geometry={nodes.Cube018.geometry} material={materials.Kevlar} position={[-1.505, 4.237, 0.069]} rotation={[0, 1.557, 0.043]} />
      <motion.mesh animate={{scale: section ===0 ? 0.3 : 0}} geometry={nodes.Cube000.geometry} material={materials.Kevlar} position={[-1.505, 4.382, 0.075]} rotation={[0, 1.557, 0.043]} />
      <motion.mesh animate={{scale: section ===0 ? [0.217, 0.3, 0.223] : [0, 0, 0]}}  geometry={nodes.Cube019.geometry} material={materials.Aluminium} position={[2.092, 2.511, 0.34]} rotation={[0, 1.557, -0.106]} />
      <motion.mesh animate={{scale: section ===0 ? [0.217, 0.3, 0.223] : [0, 0, 0]}}  geometry={nodes.Cube020.geometry} material={materials.Aluminium} position={[-1.508, 2.511, 0.29]} rotation={[0, 1.557, -0.106]} />
      <motion.mesh animate={{scale: section ===0 ? [0.217, 0.3, 0.223] : [0, 0, 0]}}  geometry={nodes.Cube021.geometry} material={materials.Kevlar} position={[2.092, 2.511, 0.345]} rotation={[0, 1.557, -0.106]} />
      <motion.mesh animate={{scale: section ===0 ? [0.217, 0.3, 0.223] : [0, 0, 0]}}  geometry={nodes.Cube026.geometry} material={materials.Kevlar} position={[-1.509, 2.512, 0.359]} rotation={[-Math.PI, -1.557, 3.036]}  />
 
          <motion.group receiveShadow castShadow position={[14.633, -1.27, 6.594]} rotation={[Math.PI / 2, 0, 0]} animate={{scale : section === 0 ? 2.021 : 0}}>
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_1'].geometry} material={materials['Material.021']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_2'].geometry} material={materials['1042']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_3'].geometry} material={materials['1053']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_4'].geometry} material={materials['1045']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_5'].geometry} material={materials['1055']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_6'].geometry} material={materials['1043']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_7'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_8'].geometry} material={materials['Material.003']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_9'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_10'].geometry} material={materials['Material.005']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_11'].geometry} material={materials['Material.006']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_12'].geometry} material={materials['Material.007']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_13'].geometry} material={materials['Material.014']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_14'].geometry} material={materials['Material.015']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_15'].geometry} material={materials['Material.016']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_16'].geometry} material={materials['Material.019']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_17'].geometry} material={materials['Material.022']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_18'].geometry} material={materials['Material.030']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_19'].geometry} material={materials['Material.025']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_20'].geometry} material={materials.Material} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_21'].geometry} material={materials['Material.027']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_22'].geometry} material={materials['Material.028']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_23'].geometry} material={materials['Material.029']} />
      </motion.group>
      <motion.mesh geometry={nodes.Plane.geometry} material={materials['Material.023']} position={[6.133, 0, 0]} animate={{scale : section == 0 ? 63.408 : 0}} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.009']} position={[6.281, 8.42, -8.372]} scale={[1.871, 3.289, 1.871]} />
    </group>
  )
}

useGLTF.preload('/fullDeskSetup.glb')
